### Get Category for Guest
GET http://localhost:3010/guest/category
Accept: application/json

### Get Item for Guest (All)
GET http://localhost:3010/guest/item
Accept: application/json

### Get Item for Guest (Category)
GET http://localhost:3010/guest/item?category=gas
Accept: application/json

### Get Item for Guest (Search)
GET http://localhost:3010/guest/item?search=gas
Accept: application/json

### Get Item for Guest (Search with Category)
GET http://localhost:3010/guest/item?search=gas&category=gas
Accept: application/json

### Register
POST http://localhost:3010/auth/register
Content-Type: application/json

{
  "fullname": "rafa",
  "username": "rafa",
  "email": "rafa@rafa.id",
  "password": "rafa1234",
  "repeat_password": "rafa1234"
}
> {%
    const {data} = response.body;
    const {token, id} = data;
    client.global.set("auth_token", token);
    client.global.set("id", id);
%}

### Login
POST http://localhost:3010/auth/login
Content-Type: application/json

{
  "username": "rafa",
  "password": "rafa1234"
}
> {%
    const {data} = response.body;
    const {token,id} = data;
    client.global.set("auth_token", token);
    client.global.set("id", id);
%}

### Get User for Admin
GET http://localhost:3010/admin/user
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get User Address for Admin
GET http://localhost:3010/admin/user
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": "{{id}}"
}

### Get Category for Admin
GET http://localhost:3010/admin/category
Accept: application/json
Authorization: Bearer {{auth_token}}

### Create Category for Admin
POST http://localhost:3010/admin/category
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Fruit"
}

### Update Category for Admin
PATCH http://localhost:3010/admin/category
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": "d6fa1b73-f379-4607-b860-667deb4678be",
  "name": "Fruit"
}

### Delete Category for Admin
DELETE http://localhost:3010/admin/category
Accept: application/json
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": "d6fa1b73-f379-4607-b860-667deb4678be"
}

### Get Item for Admin (All)
GET http://localhost:3010/admin/item
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Item for Admin (Category)
GET http://localhost:3010/admin/item?category=gas
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Item for Admin (Search)
GET http://localhost:3010/admin/item?search=gas
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Item for Admin (Search with Category)
GET http://localhost:3010/admin/item?search=gas&category=gas
Accept: application/json
Authorization: Bearer {{auth_token}}

### Get Address for User
GET http://localhost:3010/user/address
Authorization: Bearer {{auth_token}}

### Add item for Admin
POST http://localhost:3010/admin/item/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Gas",
  "description": "GasElpidio"
}
> {%
    const {data} = response.body;
    const {id} = data;
    client.global.set("item_id", id);
%}

### Add item type for Admin
POST http://localhost:3010/admin/item/type/add
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "itemId": "a",
  "type": "Refill 3Kg",
  "price": 200,
  "stock": 100
}
